### ISSUE TITLE
Enhancement - Show on hover

### ISSUE THREAD

**Issue by pykong** [chintown/monocle#10]
@chintown Thanks for putting up this neat little Chrome extension. I see a lot of potential in it.

It occurs to me that I am not the only one who struggles with the way the mini map is triggered:
https://github.com/chintown/monocle/issues/6#issue-310142927

Currently, there are only two ways to produce the minimap:
- _manually_: Requires to click on the extensions symbol to show or hid => **Tedious**
- _automatic_: Triggered by each scroll even => **Irritating** as the minimap constantly dances between shown and hidden

What could be a better way to trigger the map?
I have some experience in UX engineering. This question is actually a bit tricky.
The best solution indeed would be to reserve some screen dedicated to the mini-map only, which will be alway shown there. Probably even replacing the native scrollbar, as suggested in :
https://github.com/chintown/monocle/issues/7

Yet, especially on smaller screens, this might be too much of a loss.
The only other way I can come up with is to infer the intent to show the minimap from the cursor position. 

For example, when hovering in the top right corner, or even on the native scroll bar itself the minimap will appear. On leaving that area it will automatically be hidden.

**EDIT:**
It appears this behavior is already implemented to some degree. Yet, it requires to position the cursor at narrow strip neighboring the scroll bar. We might just widen this trigger area to make it more easy to use.

**Comment by chintown** [comment]
Hi @pykong, thanks for reaching out and providing such a thorough input!

Having a balanced and intuitive UX is an interesting challenge especially this is not a first-party feature : P

As you mentioned, some people suggested reserving a screen/viewport area dedicated to the mini-map. I actually tried that before but realized changing the original _page_ size is quite obtrusive and not all web pages are happy with that. It will make unpredictable page breakages. 

Technically, hiding the native scrollbar is achievable. But it's also very aggressive because the mini-map is somehow not guaranteed to work all the time. 

I agree triggered by each scroll could be irritating. Currently, setting the auto-hide delay to zero is a workaround to stop showing mini-map on scroll.

Making the trigger area larger is a good suggestion. I might make a sticky _label_ at middle of the right edge rather than relying on the border of mini-map. Lots of website have clickable targets at top-right corner (e.g. login button); I don't want to make a wide border on top of them. I will prioritize this feature.

**Comment by pykong** [comment]
Seems monocle got an update and the feature is now implemented.
Works fine. Thanks!
